# cloudbuild-preview.yaml
# This configuration is triggered on pull requests to the 'main' branch to preview changes.

steps:
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  args:
    - 'infra-manager'
    - 'deployments'
    - 'preview'
    - 'projects/id-thoughtparameters/locations/us-central1/deployments/thoughtman-deployment'
    - '--service-account=projects/id-thoughtparameters/serviceAccounts/infra-manager-sa@id-thoughtparameters.iam.gserviceaccount.com'
    - '--git-source-commit=${_HEAD_COMMIT_SHA}'