# cloudbuild-apply.yaml
# This configuration is triggered on pushes to the 'main' branch to deploy changes.

steps:
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  args:
    - 'infra-manager'
    - 'deployments'
    - 'apply'
    - 'projects/id-thoughtparameters/locations/us-central1/deployments/thoughtman-deployment'
    - '--service-account=projects/id-thoughtparameters/serviceAccounts/infra-manager-sa@id-thoughtparameters.iam.gserviceaccount.com'
    - '--git-source-commit=${COMMIT_SHA}'